#! /bin/bash
#compile new version of coffee-chain using previously published version
echo -e "\n>>> Compiling tests using previous version of coffee-chain\n"
grunt --gruntfile precompile.coffee

#remove tasks loader for previous version of coffee-chain
#sed -i -e "s/grunt.loadNpmTasks('grunt-coffee-chain');/grunt.loadNpmTasks('grunt-coffee-chain');/g" Gruntfile.js

#coffescript is compiling on mac in different way for an unknown reason. will investigate
if  [[ "$OSTYPE" == "darwin"* ]]; then
  cp test/expected/mac/* test/expected/
else
  cp test/expected/linux/* test/expected/
fi

echo -e "\n>>> Compiling coffee-chain\n"
#compile test cases using new version of coffee-chain
grunt --gruntfile Gruntfile.js
rm test/expected/*.js
