#! /bin/bash
#compile new version of coffee-chain using previously published version
grunt --gruntfile Gruntfile.coffee compile  --force

#remove tasks loader for previous version of coffee-chain
sed -i -e "s/grunt.loadNpmTasks('grunt-coffee-chain');//g" Gruntfile.js

#hack for mac
if [ -f Gruntfile.js-e ]
then
    rm Gruntfile.js-e
fi

#compile test cases using new version of coffee-chain
grunt --gruntfile Gruntfile.js test

